### ISSUE TITLE
Null source exception

### ISSUE THREAD

**Issue by hadim** [fiji/TurboReg#1]
This plugin does not work anymore on latest Fiji installation. See the thread : http://imagej.1557.x6.nabble.com/Using-Turboreg-plugin-for-imagej-td5011964.html

The error is the following : 

```
(Fiji Is Just) ImageJ 2.0.0-rc-30/1.49s; Java 1.7.0_79 [64-bit]; Linux
3.16.7-031607-generic; 29MB of 6603MB (<1%)

java.lang.IllegalArgumentException: null source
at java.util.EventObject.<init>(EventObject.java:56)
at java.awt.AWTEvent.<init>(AWTEvent.java:337)
at java.awt.event.InvocationEvent.<init>(InvocationEvent.java:285)
at java.awt.event.InvocationEvent.<init>(InvocationEvent.java:174)
at sun.awt.X11.XBaseMenuWindow.dispose(XBaseMenuWindow.java:907)
at java.awt.MenuComponent.removeNotify(MenuComponent.java:310)
at java.awt.Menu.removeNotify(Menu.java:198)
at java.awt.Component.removeNotify(Component.java:6991)
at java.awt.Container.remove(Container.java:1199)
at java.awt.Container.remove(Container.java:1257)
at turboRegPointToolbar.<init>(TurboReg_.java:5607)
at turboRegDialog.<init>(TurboReg_.java:1501)
at TurboReg_.run(TurboReg_.java:383)
at ij.IJ.runUserPlugIn(IJ.java:199)
at ij.IJ.runPlugIn(IJ.java:163)
at ij.Executer.runCommand(Executer.java:131)
at ij.Executer.run(Executer.java:64)
at java.lang.Thread.run(Thread.java:745)
```

Bug seems to be located in this function
(https://github.com/fiji/TurboReg/blob/master/src/main/java/TurboReg_.java#L5607):

``` java
public turboRegPointToolbar (
    final Toolbar previousToolbar
    ) {
    previousInstance = previousToolbar;
    instance = this;
    final Container container = previousToolbar.getParent();
    final Component[] component = container.getComponents();
    for (int i = 0; (i < component.length); i++) {
        if (component[i] == previousToolbar) {
            container.remove(previousToolbar); // <---- HERE
            container.add(this, i);
            break;
        }
    }
    resetButtons();
    down[currentTool] = true;
    setTool(currentTool);
    setForeground(Color.black);
    setBackground(gray);
    addMouseListener(this);
    container.validate();
} /* end turboRegPointToolbar */
```

I guess the issue comes from an API breakage.

I really would like to help on this but after some digging I can't find a way to resolve it.

**Comment by LeeKamentsky** [comment]
Hi Hadim,
I'm seeing this problem myself, but when I close down ImageJ in a more general way. I think it's a bug in OpenJDK 1.7 (for instance see https://bugs.openjdk.java.net/browse/JDK-8029252?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel&ei=-3e3VcCjKYapgwTAuLngCA&usg=AFQjCNHrBtUpqA8jzijFUH3wxawlIEsAZQ&sig2=8JWqt3WxivgC3G-NBKx7mw). I'm not sure what to do about it, may try reverting to 1.6.

**Comment by hadim** [comment]
Thank you @LeeKamentsky for the information.

I will wait for 1.7 fix then and go back to 1.6 when needed in the meantime :-(

**Comment by LeeKamentsky** [comment]
I noticed that my build started to fail when the RPM upgraded from
1.7.0-openjdk-1.7.0.79 to 1.7.0-openjdk-1.7.0.85. I am testing right now by
reverting to 1.7.0.79 and will report if that works.

**Comment by ctrueden** [comment]
Out of curiosity, does the problem also happen with Java 8?

**Comment by LeeKamentsky** [comment]
Java 8: Not my monkeys, not my circus (yet). At this point, our build is approaching a cusp of reproducibility. If you have Docker installed somewhere and clone the CellProfiler GIT repository do the following:
    docker run --rm=true -v "$PWD":/jenkins/CellProfiler:rw centos:centos6.6 /jenkins/CellProfiler/jenkins/linux/build_everything.sh

it should build and test CellProfiler and you can change the JAVA_VERSION and JAVA_PATCH_VERSION in the file, https://github.com/CellProfiler/CellProfiler/blob/2.1.1-janssen/jenkins/build_cellprofiler.sh, to pick out whatever you want. Also our POM has ImageJ locked down to sometime in April I think.

You may have to wait quite a while - the build takes several hours to complete when we run it here.

**Comment by ctrueden** [comment]
@LeeKamentsky Glad to hear the build is (almost) reproducible! Too bad it takes so long to run—I'm a bit surprised by that actually.

**Comment by LeeKamentsky** [comment]
It literally builds the world. Not the compilers, the high-performance matrix libraries and Java, but Python and all its base libraries, the UI toolkits and all the scientific library dependencies.

**Comment by ctrueden** [comment]
Wow! :open_mouth:

**Comment by LeeKamentsky** [comment]
OK build is done and it passed - so as far as CellProfiler is concerned, JDK 1.7.0.79 is good and 1.7.85 is bad. I see from the above that you are using 1.7.0.79, so maybe 1.7.0.85 will work for you (or whatever version I had before 1.7.0.79, because it could be that going to 1.7.0.79 caused the CellProfiler build to break.

I did go through quite a bit to get CellProfiler to close ImageJ using 1.7.0.79. (See https://github.com/CellProfiler/CellProfiler/blob/2eec78bba40ff4dc80e80e9c449ac391f5d99e29/cellprofiler/utilities/cpjvm.py#L242) I had to manually destroy the image windows, then manually destroy the menus, then remove whatever windows were left open. Disturbingly random! Someone forgot to clear a handle somewhere deep inside AWT I guess. Does anyone remember the days when you'd write a C program, compile a single file and run a.out?

**Comment by ctrueden** [comment]
[Bwaaaa ha ha](https://github.com/CellProfiler/CellProfiler/blob/2eec78bba40ff4dc80e80e9c449ac391f5d99e29/cellprofiler/utilities/cpjvm.py#L289-L293)!

**Comment by LeeKamentsky** [comment]
LOL ok. Let's have a moment of gratefulness for Wayne who, despite some quirky ways of doing things, gave us something that we could actually use. Maybe he was copying the [Windows start button](http://blogs.msdn.com/b/oldnewthing/archive/2003/07/22/54559.aspx) which you have to press in order to shut things down.

**Comment by ctrueden** [comment]
Hear, hear.

**Comment by ctrueden** [comment]
@hadim Any updates? Still seeing this bug? How about with Java 8?

**Comment by hadim** [comment]
Just tested with an updated Fiji installation and the bug is not here anymore (with java 1.7). Maybe we can close this for now.

**Comment by ctrueden** [comment]
Thanks @hadim!
